---

- name: Reload NFS exports
  ansible.builtin.command:
    cmd: "exportfs -ra"
  listen: "reload nfs exports"

- name: Reload Firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted