---
- name: Create Node Exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin
    create_home: false

- name: Download Node Export binary
  ansible.builtin.unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /usr/local/bin
    remote_src: true
    extra_opts: [--strip-components=1]
    mode: '0755'
    owner: node_exporter
    group: node_exporter

- name: Open Node Exporter port
  ansible.builtin.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
  notify: Reload Firewall

- name: Create node Exporter Systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: Restart node_exporter

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
