---
- name: Restart vault
  ansible.builtin.systemd:
    name: vault
    state: restarted

- name: Reload firewall  # Fixed handler name
  ansible.builtin.systemd:
    name: firewalld
    state: restarted