---
- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: false

- name: Ensure SSH client is installed
  ansible.builtin.package:
    name: "{{ ssh_client_packages }}"
    state: present
  register: pkg_result
  # Some platforms may already have ssh; no harm if package name missing
  failed_when: false

- name: Ensure ~/.ssh exists with strict permissions
  ansible.builtin.file:
    path: "{{ ssh_client_dir }}"
    state: directory
    mode: "0700"

- name: Create {{ ssh_client_key_type }} keypair if missing
  community.crypto.openssh_keypair:
    path: "{{ ssh_client_key_path }}"
    type: "{{ ssh_client_key_type }}"
    comment: "{{ ssh_client_key_comment }}"
    mode: "0600"
  register: keypair

- name: Cache the public key for downstream plays
  ansible.builtin.set_fact:
    ssh_client_public_key: "{{ keypair.public_key }}"
  cacheable: true
