- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Reload Firewall
  ansible.builtin.systemd:
    name: firewalld 
    state: restarted
