---

- name: Check if IOMMU is already enabled
  ansible.builtin.shell: "dmesg | grep -E 'IOMMU enabled|AMD-Vi enabled'"
  register: iommu_check
  changed_when: false
  failed_when: false

- name: Configure IOMMU
  block:
    - name: Enable IOMMU in GRUB
      ansible.builtin.lineinfile:
        path: "{{ grub_file }}"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(?!.*{{ iommu_cmd }})(.*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ iommu_cmd }} iommu=pt"'
        backrefs: yes
      when: iommu_check.rc != 0
      register: grub_updated

    - name: Ensure required kernel modules are loaded
      ansible.builtin.lineinfile:
        path: "{{ modules_file }}"
        line: "{{ item }}"
        create: yes
      loop: "{{ vfio_modules }}"
      register: modules_updated

    - name: Set VFIO unsafe interrupts
      ansible.builtin.lineinfile:
        path: "{{ iommu_file }}"
        line: "options vfio_iommu_type1 allow_unsafe_interrupts=1"
        create: yes
      register: iommu_config_updated

    - name: Set KVM ignore_msrs
      ansible.builtin.lineinfile:
        path: "{{ kvm_file }}"
        line: "options kvm ignore_msrs=1"
        create: yes
      register: kvm_config_updated

    - name: Apply changes if needed
      block:
        - name: Update GRUB
          ansible.builtin.command: update-grub
          when: grub_updated.changed

        - name: Load kernel modules immediately
          ansible.builtin.modprobe:
            name: "{{ item }}"
            state: present
          loop: "{{ vfio_modules }}"
          when: modules_updated.changed
          ignore_errors: true

        - name: Update initramfs
          ansible.builtin.command: update-initramfs -u
          when: grub_updated.changed or modules_updated.changed or 
                iommu_config_updated.changed or kvm_config_updated.changed

        - name: Reboot if required
          ansible.builtin.reboot:
            msg: "Rebooting to enable IOMMU changes"
            connect_timeout: 5
            reboot_timeout: 300
            post_reboot_delay: 30
          when: grub_updated.changed or modules_updated.changed or 
                iommu_config_updated.changed or kvm_config_updated.changed
