---

- name: Correct Proxmox VE sources
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian bookworm main contrib
      deb http://deb.debian.org/debian bookworm-updates main contrib
      deb http://security.debian.org/debian-security bookworm-security main contrib
  register: debian_sources

- name: Suppress non-free firmware warnings
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
    content: 'APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";'
  register: firmware_warnings

- name: Disable PVE Enterprise repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    content: |
      # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
  register: disable_enterprise

- name: Enable PVE No-Subscription repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-install-repo.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
  register: enable_no_subscription

- name: Disable subscription nag
  block:
    - name: Add script to remove subscription nag
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/no-nag-script
        content: 'DPkg::Post-Invoke { "dpkg -V proxmox-widget-toolkit | grep -q ''/proxmoxlib\\.js$''; if [ \\$? -eq 1 ]; then { echo ''Removing subscription nag from UI...''; sed -i ''/.*data\\.status.*{/{s/\\!//;s/active/NoMoreNagging/}'' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi"; };'
      register: no_nag_script

    - name: Reinstall proxmox-widget-toolkit to apply changes
      ansible.builtin.apt:
        name: proxmox-widget-toolkit
        state: present
        force: yes
      when: no_nag_script.changed

- name: Update Proxmox VE
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update
      when: proxmox_update_cache | default(false)

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade
      when: proxmox_upgrade | default(false)

- name: Reboot Proxmox VE if required
  ansible.builtin.reboot:
    msg: "Rebooting to apply repository changes"
    connect_timeout: 5
    reboot_timeout: 300
    post_reboot_delay: 30
  when: 
    - proxmox_reboot | default(false)
    - (debian_sources is defined and debian_sources.changed) or
      (disable_enterprise is defined and disable_enterprise.changed) or
      (enable_no_subscription is defined and enable_no_subscription.changed) or
      (apt_upgrade is defined and apt_upgrade.changed)
