---
- name: Prepare localhost SSH client + keypair
  hosts: localhost
  gather_facts: true
  roles:
    - role: ssh_client

- name: Authorize localhost key on remote servers
  hosts: all
  gather_facts: false
  roles:
    - role: ssh_authorize
