---
- name: Add HashiCorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true

- name: Install Vault
  ansible.builtin.package:
    name: vault
    state: present

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: vault
    mode: '0750'
  loop:
    - "{{ vault_storage_path }}"

- name: Configure Vault
  ansible.builtin.template:
    src: templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0640'
  notify: Restart vault

- name: Open vault ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 8199/tcp
    - 8200/tcp
  notify: Reload firewall

- name: Add VAULT_ADDR to system environment
  ansible.builtin.shell: |
    export VAULT_ADDR="http://{{ ansible_host }}:8200"

- name: Start and enable Vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true
