# Example Galaxy requirements; customize per your playbooks
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.crypto
  - name: ansible.posix
  - name: community.proxmox
roles: []