---
- name: Restart grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

- name: Reload Firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted