---
- name: Write repository information in Kubernetes repo file
  ansible.builtin.blockinfile:
    path: "/etc/yum.repos.d/kubernetes.repo"
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl={{ kubernetes_repo_url }}
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey={{ kubernetes_gpg_key }}
    create: true
    mode: "0644"

- name: Refresh pacakage cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.package:
    name:
      - "kubelet-{{ kubernetes_version }}"
      - "kubeadm-{{ kubernetes_version }}"
      - "kubectl-{{ kubernetes_version }}"
    state: present

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
