---
- name: Disable swap temporarily if enabled
  ansible.builtin.shell:
    cmd: "swapon --show | grep -q swap && swapoff -a || true"
  register: swapoff_result
  changed_when: swapoff_result.rc == 0

- name: Disable swap permanently in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '\s+swap\s+'
    state: absent

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl parameters for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Ensure sysctl settings persist
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: '0644'

- name: Apply sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false

- name: Configure firewall for Control Plane nodes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
  when: inventory_hostname in groups['prod_control_plane']
  notify: Reload firewall

- name: Configure firewall for Worker nodes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 10250/tcp
    - 30000-32767/tcp
  when: inventory_hostname in groups['prod_workers']
  notify: Reload firewall

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
- name: Populate /etc/hosts file using template
  ansible.builtin.template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Force handlers to run now
  meta: flush_handlers
